### ISSUE TITLE
pyflame shows cpu is high idle, but nmon command shows cpu is full load.

### ISSUE THREAD

**Issue by coder-zhuyu** [uber/pyflame#102]
I run tornado with aiomysql on ubuntu 16.04, python version is 3.5.2.
I only execute a simple select db query on mysql.
pyflame shows cpu is high idle, but nmon command shows cpu is full load.
It's so strange?

**Comment by eklitzke** [comment]
Is this with or without `--threads`?

**Comment by coder-zhuyu** [comment]
pyflame 1.4.4, Compiled Jul 26 2017, 10:43:24 by GCC 5.4.0 20160609
the app is not threaded.
sudo pyflame -s 5 -r 0.001 -o prof.txt 6505
the svg picture is show:[https://coder-zhuyu.github.io/images/prof-tornado.svg](url)

**Comment by coder-zhuyu** [comment]
pyflame 1.4.4, Compiled Jul 26 2017, 10:43:24 by GCC 5.4.0 20160609
The app is not threaded.
sudo pyflame -s 5 -r 0.001 -o prof.txt 6505
The flame picture is shown: https://coder-zhuyu.github.io/images/prof-tornado.svg

**Comment by eklitzke** [comment]
This looks pretty normal to me. You can use `-x` to exclude the idle times, but you probably already know that.

My guess is that if you use GDB to attach to the process, you will see that it's frequently blocking in the Tornado event loop. IIRC, you'll see a call to something like `__epoll_wait()` as frame 0 as reported by the GDB `bt` command. Try getting a backtrace from GDB a dozen times or so, and if Pyflame says your program is idle about 50% of the time then you should see the `__epoll_wait()` call about 50% of the time as well.

**Comment by coder-zhuyu** [comment]
I understand.
Thank you for your answer.
