### ISSUE TITLE
Not working with numba's JIT (Pyflame not following all child processes?)

### ISSUE THREAD

**Issue by jackvreeken** [uber/pyflame#122]
I was using pyflame to profile an application that uses numba for JIT compilation. It turns out the ```from numba import jit``` is enough to cause any profile with the `-t` option to exit too early. I tried using the `--threads` option, but that does help either. For longer running processes it is still possible to attach to the eventual pid manually, but this is of course not feasible for those that exit within a few seconds.

Would it be possible to wait for other child processes as well, or should pyflame already be doing that (with numba the cause of the problem)? I am not entirely sure how to check this myself.

As an example, I took the `sleeper.py` script, and added ```from numba import jit``` in the import section:

```Python
import os
import sys
import time
from numba import jit

def main():
    sys.stdout.write('%d\n' % (os.getpid(), ))
    sys.stdout.flush()
    for i in range(10):
        time.sleep(0.1)
        target = time.time() + 0.1
        while time.time() < target:
            pass


if __name__ == '__main__':
    main()
```

**Comment by eklitzke** [comment]
Ack. The PR I just put up seems to make this less bad, but doesn't quite fix it. From what I can tell, tracing a numba script with Pyflame causes `SIGABRT` to be delivered to the child process.

**Comment by eklitzke** [comment]
Looks like the abort issue is something else -- I can reliably cause numba to crash with a segfault when I fork in a Python script using the JIT. F Can you verify if this change fixes the application you're using? Clone the branch `fix_sigchld` from my fork of this repo to test.

**Comment by jackvreeken** [comment]
It still fails to attach to the (child?) process after the JIT is done. So the only thing I see in the profile when running ```pyflame -o out.txt -t python sleeper.py``` using the code above is import statements (frozen importlib stuff). I could try to dive a little in numba and see how it spawns the new process with compiled code, but it will a few weeks before I can find time for that. As I mentioned, attaching with ```-p``` to the eventual pid is still workable for now, but is not as convenient.

**Comment by eklitzke** [comment]
Closing this for now, although I need to figure out how to add a test case...
