### ISSUE TITLE
How to profile memory usage

### ISSUE THREAD

**Issue by jethar** [uber/pyflame#125]
How can I profile memory leak using the pyflame. I have a flask application running on python 3.6. As per my understanding from teh readme, by default it gives CPU flame graphs.

In the blog - https://eng.uber.com/pyflame/  there is reference to profiling memory characteristics.

**Comment by eklitzke** [comment]
Pyflame does not support memory profiling. The blog post just says that we flame graphs are useful for memory profiling as well.

I suggest using tracemalloc if you'd like to do memory profiling: https://docs.python.org/3/library/tracemalloc.html
