### ISSUE TITLE
Work with uwsgi run on Docker

### ISSUE THREAD

**Issue by Cyansilver** [uber/pyflame#145]
- `pyflame -v`: pyflame 1.3.1
 - Version of the Python interpreter you are profiling: 3.6
 - The exact text of any error messages: no error message

 Hi,

I'm trying run pyflame for my uwsgi application on Docker. I use the following command to get the docker container pid:
`sudo docker inspect -f '{{.State.Pid}}' <container id>`

When I run the command:
` sudo pyflame -s 86400 -r 0.01 <pid> | ./../FlameGraph/flamegraph.pl > myprofile.svg`

It hangs for a while and then exits. When I checked the svg file. It only has `idle`

Other information are:
- python version in host is 2.7
- python version in docker is 3.6
- uwsgi run under socket not http socket

**Comment by Cyansilver** [comment]
I know the problems:
- When I clone the repo, it's on master branch and when compiled it's on version 1.3.1. I need to change to the tag v1.6.3
- I use ubuntu 16.04 so don't have python 3.6 so when run ./configure it doesn't support 3.6

So my new issue is when I install python 3.6 via **ppa:jonathonf/python-3.6**, it doesn't create .pc file

I wonder how can I create .pc file for python-3.6?

**Comment by eklitzke** [comment]
The .pc file should be part of the -devel package.
