### ISSUE TITLE
x86_64 ubuntu14.04 not work for Failed to seize PID

### ISSUE THREAD

**Issue by xiazhibin** [uber/pyflame#160]
Make sure that these boxes are checked before submitting your issue:
`pyflame -v` shows `pyflame 1.6.6 linux-gnu x86_64 (ABI list: 26 34)`
`uname -a` shows `x86_64 GNU/Linux`

when I run `make check` 

all FAILURES is that `Failed to seize PID`

**Comment by unaplugin** [comment]
```Failed to seize PID``` error too.
It cannot seize any PID on my PC.
Does anybody can help??
