### ISSUE TITLE
C compiler needs C++ standard option?

### ISSUE THREAD

**Issue by Patterner** [uber/pyflame#20]
Running configure with clang/clang++ 3.9 fails

> checking whether C compiler accepts "-std=c++11"... no
> checking whether C compiler accepts "-std=c++0x"... no
> configure: error: failed to detect C++11 support

> configure:3938: clang -c -std=gnu11 -march=native -O3 -pipe  -std=c++11  conftest.c >&5
> error: invalid argument '-std=c++11' not allowed with 'C/ObjC'

Not sure why the C compiler has to support that.

**Comment by jeevandev** [comment]
The pyflame code requires C++ 11 support. Also if you are trying this on Mac, it won't work.

**Comment by eklitzke** [comment]
This works if you use clang++. Try:

```
CC=clang++ make
```

**Comment by Patterner** [comment]
`AX_CHECK_COMPILE_FLAG` is checking the C compiler, not the C++ compiler. It doesn't make sense.

If I use `AX_CXX_COMPILE_STDCXX_11` instead it works.

If I add `AC_LANG(C++)` before `AX_CHECK_COMPILE_FLAG` it work.

`CXX` is set to `clang++`, but the configure script is checking the C compiler.

(autoconf 2.69-10 & autoconf-archive 20160320-1)
