### ISSUE TITLE
It doesn't work with app under uwsgi

### ISSUE THREAD

**Issue by alexander-akhmetov** [uber/pyflame#23]
Hi!

It is great tool, but I have problems with app under uwsgi. Pyflame shows only `(idle)` for it.  Could you help me please?

Python application (`app.py`):

```python
# -*- coding: utf-8 -*-
from flask import Flask


app = Flask(__name__)


@app.route('/')
def hello_world():
    return 'Hello, World!'
```

Starting uwsgi:

```console
[~/pyflame_test]$ uwsgi --workers 1 --module app:app --http-socket=127.0.0.1:8011
*** Starting uWSGI 2.0.12 (64bit) on [Wed Oct  5 04:53:43 2016] ***
...
spawned uWSGI worker 1 (and the only) (pid: 29707, cores: 1)
```

Starting pyflame:
```console
sudo ./pyflame 29707 -s 5
```

Making http request:
```console
[~/]$ curl http://127.0.0.1:8011/
Hello, World!
```

pyflame has printed: `(idle) 4363`

If I run `strace` to this worker I'll see:

```console
strace -p 29707
...
read(5, "GET / HTTP/1.1\r\nUser-Agent: curl"..., 4096) = 78
writev(5, [{"HTTP/1.1 200 OK\r\nContent-Type: t"..., 79}, {"Hello, World!", 13}], 2) = 92
...
```

```console
[~/pyflame_test]$ uwsgi --version
2.0.12
```

**Comment by eklitzke** [comment]
Thanks for the bug report. I believe that I found the issue and I've pushed the fix to the `uwsgi` branch. Can you try building pyflame from that branch and let me know if it fixes the issue for you?

**Comment by alexander-akhmetov** [comment]
Yes, it works well now. Thank you!
