### ISSUE TITLE
Empty flame graphs when there's a lot of idle time

### ISSUE THREAD

**Issue by mbenbernard** [uber/pyflame#46]
I ran this very simple Python program:

    import time

    def compute(x):
        res = x**2*7/9+31
        return res

    index = 0
    while True:
        index += 1
        compute(index)
        time.sleep(1)

And I profiled it using the following command line:

pyflame -s 20 -r 0.00000000000001 {pid} | ./flamegraph.pl > flames.svg

I understand that compute() completes and returns very rapidly. And I also understand that time.sleep() takes the majority of my program's time. However, given that the sampling interval is very small, I would have expected the flame graph to contain at least a few samples for the compute() function. But this isn't the case; the flame graph always shows 100% idle time.

Now, if I considerably reduce the value passed to time.sleep() (e.g. 0.0000001) in my program, then the flame graph contains samples for the compute() method, as we could expect.

Is this the normal behaviour of pyflame? Or is it a technical limitation?

Thanks!

**Comment by eklitzke** [comment]
What is the actual wall time vs CPU time for this script, if you just run it with `time`? If the ratio is too extreme you might have problems observing the function.

Also FYI there is some overhead to sampling (on the order of 10s or 100s of microseconds, IIRC) so if you set the `-r` option to a value that's too small it won't actually be able to sample at that rate.

**Comment by mbenbernard** [comment]
I ran `time` against the above script for ~50s and here are the returned stats:

real    0m52.225s
user    0m0.060s
sys     0m0.034s

So the CPU time represents ~0.18% of the total execution time. Considering the sampling overhead that you mentioned, I guess that what I'm seeing is normal.

Thanks for the follow-up!
