### ISSUE TITLE
Pyflame always runs as if I had passed --threads

### ISSUE THREAD

**Issue by josephaltmaier** [uber/pyflame#62]
Using pyflame 1.3.1 with Python 2.7.12 on Ubuntu 16.04 pyflame always returns output as if I had passed the --threads option.  This makes it hard to get a useful profile of the running thread.  Here is some sample code that should illustrate the problem:
~~~~
import threading, time

def main():
    busyThread = threading.Thread(target=busy)
    busyThread.start()
    while True:
        time.sleep(1000)

def busy():
    number = 0
    while True:
        number += 1

if __name__ == '__main__':
    main()
~~~~
Here is some sample output
sudo pyflame -s 0 PID results in:
profilable.py:<module>:15;profilable.py:main:7 1
/usr/lib/python2.7/threading.py:__bootstrap:774;/usr/lib/python2.7/threading.py:__bootstrap_inner:801;/usr/lib/python2.7/threading.py:run:754;profilable.py:busy:11 1

Why would -s 0 without the --threads option return with two samples?

sudo pyflame -s 0 --threads PID results in:
profilable.py:<module>:15;profilable.py:main:7 1
/usr/lib/python2.7/threading.py:__bootstrap:774;/usr/lib/python2.7/threading.py:__bootstrap_inner:801;/usr/lib/python2.7/threading.py:run:754;profilable.py:busy:12 1

This is as expected but it is identical to running pyflame without --threads

sudo pyflame -s 30 PID results in:
profilable.py:<module>:15;profilable.py:main:7 24549
/usr/lib/python2.7/threading.py:__bootstrap:774;/usr/lib/python2.7/threading.py:__bootstrap_inner:801;/usr/lib/python2.7/threading.py:run:754;profilable.py:busy:12 24548
/usr/lib/python2.7/threading.py:__bootstrap:774;/usr/lib/python2.7/threading.py:__bootstrap_inner:801;/usr/lib/python2.7/threading.py:run:754;profilable.py:busy:11 1

The total number of samples * the default sampling period exceeds the time spent profiling.  Also it seems unlikely sampling the active thread would end up in the sleeping thread so often

sudo pyflame -s 30 --threads PID results in:
profilable.py:<module>:15;profilable.py:main:7 25126
/usr/lib/python2.7/threading.py:__bootstrap:774;/usr/lib/python2.7/threading.py:__bootstrap_inner:801;/usr/lib/python2.7/threading.py:run:754;profilable.py:busy:11 12537
/usr/lib/python2.7/threading.py:__bootstrap:774;/usr/lib/python2.7/threading.py:__bootstrap_inner:801;/usr/lib/python2.7/threading.py:run:754;profilable.py:busy:12 12589

This is nearly identical to running pyflame without the --threads option

**Comment by jamespic** [comment]
I see what's happened here. The thread walking logic in `frob.cc` doesn't respect the `enable_threads_` setting - so as long as *something* holds the GIL, it'll still walk all threads. I'll take a look at this when I get chance.

**Comment by josephaltmaier** [comment]
Rerunning my tests with your changes seems to provide much more sensible results.  Thanks!
