### ISSUE TITLE
Capture memory metrics for flame charts

### ISSUE THREAD

**Issue by petroslamb** [uber/pyflame#68]
It would be most helpful to also have flame charts on memory consumption. Would you say that is easy to do?

Congrats on a great job overall.

**Comment by eklitzke** [comment]
What do you want exactly? Tracking the heap size for each snapshot would be easy, but getting true memory flamegraphs is non-trivial.

If you want to do heap profiling for Python I recommend using tracemalloc, which is integrated in Python 3. There are also patches you can apply to Python 2.x to get tracemalloc working: https://pytracemalloc.readthedocs.io/
