### ISSUE TITLE
Travis tests started failing for Python 3.4 and 3.5

### ISSUE THREAD

**Issue by eklitzke** [uber/pyflame#75]
Something about the Travis VM environment changed to cause the Python 3 tests to always fail. This is *not* related to a code change, the old revisions that were passing Travis are now failing. I installed a Trusty VM locally, and cannot reproduce the issue. So Travis changed something about their VM environment that caused the breakage.

The errors are all like:
```
       AssertionError: assert not 'Failed to PTRACE_PEEKDATA at 0x10: Input/output error\n'
```

This indicates a null pointer dereference via ptrace. Basically ptrace has a pointer to some struct and is trying to dereference a field in the struct, but the struct pointer is null.

Ideally I could get an actual VM image used by Travis so I could debug locally. Otherwise I can just try adding lots of sanity checks to the code and run many builds, and try to work things out backwards. I'm worried though that if the error is something like the ELF symbol table is different in some unusual way on Travis, that it would be extremely time consuming to debug the issue using this approach.

**Comment by jeevandev** [comment]
@eklitzke is this related to #69 ? They are hitting the same error

**Comment by eklitzke** [comment]
@jeevandev No, #69 is about Python 3.6 support. The tests started failing for Python 3.4 and 3.5.

**Comment by eklitzke** [comment]
I figured it out. This is the same issue as #69, and Travis is always running Python 3.6 instead of Python 3.4/3.5. I will create a separate issue.
