### ISSUE TITLE
Compilation failed due to `ENABLE_PY2` not defined

### ISSUE THREAD

**Issue by zhangyangyu** [uber/pyflame#90]
I can't compile pyflame successfully. My environment gets Py2.7 and the develop files are installed. See the configure log:

> checking for PY26... yes
> checking for PY34... no
> checking for PY34... no
> configure: WARNING: Building without Python 3.4/3.5 support
> checking for PY36... no
> configure: WARNING: Building without Python 3.6 support

But the compilation still fails:

> pyflame.cc:40:1: 错误：static assertion failed: Need Python2 or Python3 support to build
>  static_assert(false, "Need Python2 or Python3 support to build");

Looks to me only `ENABLE_PY26` is defined but not `ENABLE_PY2`. I temporarily change it to `ENABLE_PY26` and the build succeeds.

**Comment by eklitzke** [comment]
Thanks for the report. Yes you're right -- the code should have said `ENABLE_PY26`. I have made this change in master, and released it as Pyflame 1.4.4.

**Comment by zhangyangyu** [comment]
Thanks.
